import { type LayoutConfig } from "../layout.ts";

export const LAYOUT_FI_TUOMAS: LayoutConfig = {
  codePoints: {
    Backquote: "`~",
    Digit1: "1!",
    Digit2: "2@",
    Digit3: "3#",
    Digit4: "4$",
    Digit5: "5%",
    Digit6: "6^",
    Digit7: "7&",
    Digit8: "8*",
    Digit9: "9(",
    Digit0: "0)",
    Minus: "-_",
    Equal: "=+",
    KeyQ: "yY",
    KeyW: "uU",
    KeyE: "äÄ",
    KeyR: "gG",
    KeyT: "wW",
    KeyY: "fF",
    KeyU: "hH",
    KeyI: "kK",
    KeyO: "rR",
    KeyP: "qQ",
    BracketLeft: "[{",
    BracketRight: "]}",
    Backslash: "\\|",
    KeyA: "oO",
    KeyS: "iI",
    KeyD: "aA",
    KeyF: "eE",
    KeyG: "öÖ",
    KeyH: "jJ",
    KeyJ: "sS",
    KeyK: "tT",
    KeyL: "nN",
    Semicolon: "lL",
    Quote: ";:",
    IntlBackslash: "\\|",
    KeyZ: "zZ",
    KeyX: "xX",
    KeyC: "cC",
    KeyV: "vV",
    KeyB: "åÅ",
    KeyN: "bB",
    KeyM: "mM",
    Comma: "pP",
    Period: "dD",
    Slash: ".,",
    Space: " ",
  },
};
